'use client'

import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',

    // Hero Section
    'hero.badge': 'AI-Powered Startup Intelligence',
    'hero.title.part1': 'Founder',
    'hero.title.part2': 'Is',
    'hero.words.innovate': 'Innovate',
    'hero.words.create': 'Create',
    'hero.words.validate': 'Validate',
    'hero.words.launch': 'Launch',
    'hero.words.scale': 'Scale',
    'hero.description': 'Your AI-powered thinking partner that guides you from',
    'hero.description.highlight': ' initial spark to market success',
    'hero.description.end': ' — offering strategic insights, validation frameworks, and emotional support every step of the way.',
    'hero.button.start': 'Start Building',
    'hero.stats.features': 'AI Features',
    'hero.stats.success': 'Success Rate',
    'hero.stats.support': 'Strategic Support',

    // Benefits Section
    'benefits.badge': 'Why Choose FounderIs',
    'benefits.title': 'Your complete startup',
    'benefits.title.highlight': 'support ecosystem',
    'benefits.description': 'From initial brainstorming to market validation, strategic planning to emotional resilience — FounderIs provides the comprehensive guidance solo founders need to succeed.',
    'benefits.vision.title': 'Vision Partner',
    'benefits.vision.description': 'Interactive brainstorming sessions that help refine your ideas, explore untapped opportunities, and crystallize your core value proposition.',
    'benefits.market.title': 'Market Compass',
    'benefits.market.description': 'Guided validation frameworks and hypothesis testing to ensure product-market fit before you invest time and resources.',
    'benefits.strategic.title': 'Strategic Planner',
    'benefits.strategic.description': 'Structured business planning, financial projections, and actionable roadmaps that keep you focused on what matters most.',
    'benefits.decision.title': 'Decision Lab',
    'benefits.decision.description': 'Scenario simulations and pre-mortem analysis that help you anticipate challenges and make informed strategic choices.',
    'benefits.execution.title': 'Execution Optimizer',
    'benefits.execution.description': 'Communication assistance, productivity insights, and bottleneck identification to maximize your efficiency and impact.',
    'benefits.emotional.title': 'Emotional Anchor',
    'benefits.emotional.description': '24/7 confidential support space offering motivation, stress management, and resilience building for the founder journey.',
    'benefits.button': 'Experience the Power',

    // How It Works Section
    'howworks.badge': 'How It Works',
    'howworks.title': 'Your journey from',
    'howworks.title.highlight': 'spark to success',
    'howworks.description': 'Three core pillars of support that provide comprehensive guidance, validation insights, and emotional resilience for solo founders.',
    'howworks.step1.title': 'Thinking Partnership',
    'howworks.step1.description': 'Engage in interactive brainstorming sessions to clarify your vision, refine your value proposition, and develop strategic plans.',
    'howworks.step1.detail1': 'Interactive idea refinement',
    'howworks.step1.detail2': 'Value proposition development',
    'howworks.step1.detail3': 'Strategic planning assistance',
    'howworks.step1.detail4': 'Communication and pitch support',
    'howworks.step2.title': 'Validation Framework',
    'howworks.step2.description': 'Design and execute market validation experiments with AI-guided research to prove product-market fit.',
    'howworks.step2.detail1': 'Hypothesis testing design',
    'howworks.step2.detail2': 'Market research guidance',
    'howworks.step2.detail3': 'Customer feedback analysis',
    'howworks.step2.detail4': 'Demand assessment tools',
    'howworks.step3.title': 'Continuous Support',
    'howworks.step3.description': 'Access ongoing emotional support, productivity optimization, and strategic guidance throughout your founder journey.',
    'howworks.step3.detail1': 'Confidential emotional support',
    'howworks.step3.detail2': 'Productivity and focus coaching',
    'howworks.step3.detail3': 'Stress management techniques',
    'howworks.step3.detail4': 'Motivational reinforcement',
    'howworks.button': 'Start Your Journey',
    'howworks.subtitle': 'Join solo founders who no longer journey alone',

    // Footer Section
    'footer.badge': 'Ready to Transform?',
    'footer.title': 'Ready to transform your',
    'footer.title.highlight': 'founder journey?',
    'footer.description': 'Join solo founders who no longer navigate uncertainty alone. Get the strategic thinking partner, validation framework, and emotional support you need to succeed.',
    'footer.button.start': 'Start Building Today',
    'footer.brand.description': 'Your AI-powered thinking partner providing strategic guidance, validation frameworks, and emotional support for solo founders.',
    'footer.platform': 'Platform',
    'footer.company': 'Company',
    'footer.copyright': '© 2024 FounderIs. All rights reserved.',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.stories': 'Success Stories',
    'footer.documentation': 'Documentation',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy',

    // Features Page
    'features.badge': 'Our Features',
    'features.title': 'Powerful tools for',
    'features.title.highlight': 'startup success',
    'features.description': 'Discover the comprehensive set of AI-powered features designed to support every aspect of your entrepreneurial journey.',
    'features.ai.title': 'AI Strategy Partner',
    'features.ai.description': 'Advanced AI algorithms analyze your business model and provide personalized strategic recommendations.',
    'features.ai.detail1': 'Market analysis and insights',
    'features.ai.detail2': 'Competitive landscape mapping',
    'features.ai.detail3': 'Strategic decision support',
    'features.validation.title': 'Market Validation',
    'features.validation.description': 'Comprehensive tools to test and validate your business ideas before major investments.',
    'features.validation.detail1': 'Hypothesis testing framework',
    'features.validation.detail2': 'Customer feedback collection',
    'features.validation.detail3': 'Market demand assessment',
    'features.planning.title': 'Business Planning',
    'features.planning.description': 'Structured templates and guidance for creating robust business plans and financial projections.',
    'features.planning.detail1': 'Financial modeling tools',
    'features.planning.detail2': 'Milestone tracking',
    'features.planning.detail3': 'Resource allocation guidance',
    'features.support.title': 'Emotional Support',
    'features.support.description': '24/7 AI companion providing motivation, stress management, and mental health support.',
    'features.support.detail1': 'Stress management techniques',
    'features.support.detail2': 'Motivational coaching',
    'features.support.detail3': 'Burnout prevention',
    'features.analytics.title': 'Analytics Dashboard',
    'features.analytics.description': 'Real-time insights and metrics to track your startup progress and performance.',
    'features.analytics.detail1': 'Progress tracking',
    'features.analytics.detail2': 'Performance metrics',
    'features.analytics.detail3': 'Growth insights',
    'features.community.title': 'Founder Network',
    'features.community.description': 'Connect with like-minded entrepreneurs and access exclusive founder resources.',
    'features.community.detail1': 'Peer mentorship',
    'features.community.detail2': 'Expert workshops',
    'features.community.detail3': 'Networking events',
    'features.cta.title': 'Ready to experience the power?',
    'features.cta.description': 'Join thousands of founders who are already building successful startups with FounderIs.',

    // Pricing Page
    'pricing.badge': 'Simple Pricing',
    'pricing.title': 'Choose the plan',
    'pricing.title.highlight': 'that fits your journey',
    'pricing.description': 'Start free and scale as you grow. All plans include our core AI features and 24/7 support.',
    'pricing.popular': 'Most Popular',
    'pricing.starter.name': 'Starter',
    'pricing.starter.price': 'Free',
    'pricing.starter.description': 'Perfect for early-stage founders',
    'pricing.starter.feature1': 'Basic AI strategy sessions',
    'pricing.starter.feature2': 'Community access',
    'pricing.starter.feature3': 'Email support',
    'pricing.starter.feature4': '5 validation tests per month',
    'pricing.starter.button': 'Get Started Free',
    'pricing.pro.name': 'Professional',
    'pricing.pro.price': '$49/month',
    'pricing.pro.description': 'For serious entrepreneurs',
    'pricing.pro.feature1': 'Unlimited AI sessions',
    'pricing.pro.feature2': 'Advanced analytics',
    'pricing.pro.feature3': 'Priority support',
    'pricing.pro.feature4': 'Unlimited validation tests',
    'pricing.pro.feature5': 'Business plan templates',
    'pricing.pro.feature6': 'Founder network access',
    'pricing.pro.button': 'Start Pro Trial',
    'pricing.enterprise.name': 'Enterprise',
    'pricing.enterprise.price': 'Custom',
    'pricing.enterprise.description': 'For teams and accelerators',
    'pricing.enterprise.feature1': 'Everything in Pro',
    'pricing.enterprise.feature2': 'Team collaboration',
    'pricing.enterprise.feature3': 'Custom integrations',
    'pricing.enterprise.feature4': 'Dedicated account manager',
    'pricing.enterprise.feature5': 'Advanced security',
    'pricing.enterprise.feature6': 'Custom training',
    'pricing.enterprise.feature7': 'SLA guarantee',
    'pricing.enterprise.button': 'Contact Sales',
    'pricing.faq.title': 'Frequently Asked Questions',
    'pricing.faq.q1.question': 'Can I change my plan anytime?',
    'pricing.faq.q1.answer': 'Yes, you can upgrade or downgrade your plan at any time. Changes take effect immediately.',
    'pricing.faq.q2.question': 'Is there a free trial for paid plans?',
    'pricing.faq.q2.answer': 'Yes, we offer a 14-day free trial for all paid plans. No credit card required.',
    'pricing.faq.q3.question': 'What payment methods do you accept?',
    'pricing.faq.q3.answer': 'We accept all major credit cards, PayPal, and bank transfers for enterprise plans.',
    'pricing.faq.q4.question': 'Do you offer refunds?',
    'pricing.faq.q4.answer': 'Yes, we offer a 30-day money-back guarantee for all paid plans.',
    'pricing.faq.q5.question': 'Is my data secure?',
    'pricing.faq.q5.answer': 'Absolutely. We use enterprise-grade security and encryption to protect your data.',

    // About Page
    'about.badge': 'About FounderIs',
    'about.title': 'Empowering founders',
    'about.title.highlight': 'worldwide',
    'about.description': 'We believe every entrepreneur deserves access to world-class guidance and support, regardless of their background or resources.',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To democratize entrepreneurship by providing AI-powered guidance that was previously only available to well-connected founders with extensive networks.',
    'about.mission.description2': 'We\'re building the future where every founder has an intelligent, supportive partner available 24/7 to help them navigate the challenges of building a successful startup.',
    'about.stats.title': 'Our Impact',
    'about.stats.founders': 'Founders Supported',
    'about.stats.features': 'AI Features',
    'about.stats.support': 'Support Available',
    'about.stats.success': 'Success Rate',
    'about.values.title': 'Our Values',
    'about.values.description': 'The principles that guide everything we do and how we support founders worldwide.',
    'about.values.innovation.title': 'Innovation First',
    'about.values.innovation.description': 'We continuously push the boundaries of what\'s possible with AI to provide founders with cutting-edge tools and insights.',
    'about.values.transparency.title': 'Radical Transparency',
    'about.values.transparency.description': 'We believe in open, honest communication with our community and clear, understandable guidance.',
    'about.values.support.title': 'Founder-Centric',
    'about.values.support.description': 'Every decision we make prioritizes the founder experience and their success above all else.',
    'about.values.excellence.title': 'Excellence',
    'about.values.excellence.description': 'We maintain the highest standards in everything we do, from our AI algorithms to our customer support.',
    'about.team.title': 'Meet Our Team',
    'about.team.description': 'A diverse group of entrepreneurs, technologists, and AI experts united by a shared passion for supporting founders.',
    'about.team.ceo.role': 'CEO & Co-Founder',
    'about.team.ceo.bio': 'Serial entrepreneur with 15+ years of startup experience. Previously founded two successful companies.',
    'about.team.cto.role': 'CTO & Co-Founder',
    'about.team.cto.bio': 'AI researcher and engineer with expertise in machine learning and natural language processing.',
    'about.team.lead.role': 'Head of Product',
    'about.team.lead.bio': 'Product strategist focused on creating intuitive experiences that help founders succeed.',

    // Contact Page
    'contact.badge': 'Get in Touch',
    'contact.title': 'We\'re here to',
    'contact.title.highlight': 'help you succeed',
    'contact.description': 'Have questions about FounderIs? Need support with your startup journey? We\'d love to hear from you.',
    'contact.info.email.title': 'Email Us',
    'contact.info.email.value': 'hello@founderis.com',
    'contact.info.support.title': 'Support',
    'contact.info.support.value': 'Available 24/7',
    'contact.info.response.title': 'Response Time',
    'contact.info.response.value': 'Within 2 hours',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Your Name',
    'contact.form.name.placeholder': 'Enter your full name',
    'contact.form.email': 'Email Address',
    'contact.form.email.placeholder': 'Enter your email',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'Select a subject',
    'contact.form.subject.general': 'General Inquiry',
    'contact.form.subject.support': 'Technical Support',
    'contact.form.subject.partnership': 'Partnership',
    'contact.form.subject.feedback': 'Feedback',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us how we can help you...',
    'contact.form.submit': 'Send Message',
    'contact.info.title': 'Other ways to reach us',
    'contact.info.help.title': 'Need immediate help?',
    'contact.info.help.description': 'Check out our comprehensive help center with guides, tutorials, and FAQ.',
    'contact.info.community.title': 'Join our community',
    'contact.info.community.description': 'Connect with other founders and get support from our community.',
    'contact.info.community.button': 'Join Community',
    'contact.info.office.title': 'Our Office',
    'contact.info.office.address': 'San Francisco, CA\\nUnited States',

    // Privacy Page
    'privacy.badge': 'Privacy Policy',
    'privacy.title': 'Privacy Policy',
    'privacy.description': 'We take your privacy seriously. This policy explains how we collect, use, and protect your information.',
    'privacy.lastUpdated': 'Last updated: January 2024',
    'privacy.collection.title': 'Information We Collect',
    'privacy.collection.content': 'We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support.\\n\\nThis includes your name, email address, and any information you choose to share through our platform.',
    'privacy.usage.title': 'How We Use Your Information',
    'privacy.usage.content': 'We use the information we collect to provide, maintain, and improve our services, process transactions, and communicate with you.\\n\\nWe may also use your information to personalize your experience and provide relevant recommendations.',
    'privacy.sharing.title': 'Information Sharing',
    'privacy.sharing.content': 'We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy.\\n\\nWe may share information with service providers who assist us in operating our platform.',
    'privacy.security.title': 'Data Security',
    'privacy.security.content': 'We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.\\n\\nYour data is encrypted in transit and at rest using industry-standard encryption protocols.',
    'privacy.cookies.title': 'Cookies and Tracking',
    'privacy.cookies.content': 'We use cookies and similar technologies to enhance your experience, analyze usage patterns, and provide personalized content.\\n\\nYou can control cookie settings through your browser preferences.',
    'privacy.rights.title': 'Your Rights',
    'privacy.rights.content': 'You have the right to access, update, or delete your personal information. You may also opt out of certain communications from us.\\n\\nTo exercise these rights, please contact us using the information provided below.',
    'privacy.contact.title': 'Contact Information',
    'privacy.contact.content': 'If you have any questions about this Privacy Policy, please contact us at privacy@founderis.com.',
    'privacy.questions.title': 'Questions about privacy?',
    'privacy.questions.description': 'If you have any questions about our privacy practices, please don\'t hesitate to contact us.',
    'privacy.questions.button': 'Contact Us',

    // Terms Page
    'terms.badge': 'Terms of Service',
    'terms.title': 'Terms of Service',
    'terms.description': 'Please read these terms carefully before using our services. By using FounderIs, you agree to these terms.',
    'terms.lastUpdated': 'Last updated: January 2024',
    'terms.acceptance.title': 'Acceptance of Terms',
    'terms.acceptance.content': 'By accessing and using FounderIs, you accept and agree to be bound by the terms and provision of this agreement.',
    'terms.services.title': 'Description of Services',
    'terms.services.content': 'FounderIs provides AI-powered tools and guidance for entrepreneurs and startup founders.\\n\\nOur services include strategic planning, market validation, and emotional support through our platform.',
    'terms.account.title': 'User Accounts',
    'terms.account.content': 'You are responsible for maintaining the confidentiality of your account and password.\\n\\nYou agree to accept responsibility for all activities that occur under your account.',
    'terms.usage.title': 'Acceptable Use',
    'terms.usage.content': 'You agree to use our services only for lawful purposes and in accordance with these terms.\\n\\nYou may not use our services in any way that could damage or impair the service.',
    'terms.intellectual.title': 'Intellectual Property',
    'terms.intellectual.content': 'The service and its original content are and will remain the exclusive property of FounderIs.\\n\\nThe service is protected by copyright, trademark, and other laws.',
    'terms.payment.title': 'Payment Terms',
    'terms.payment.content': 'Certain features of our service may require payment of fees.\\n\\nYou agree to pay all applicable fees as described on our pricing page.',
    'terms.termination.title': 'Termination',
    'terms.termination.content': 'We may terminate or suspend your account immediately if you breach these terms.\\n\\nYou may also terminate your account at any time by contacting us.',
    'terms.limitation.title': 'Limitation of Liability',
    'terms.limitation.content': 'FounderIs shall not be liable for any indirect, incidental, special, or consequential damages.\\n\\nOur total liability shall not exceed the amount paid by you for our services.',
    'terms.changes.title': 'Changes to Terms',
    'terms.changes.content': 'We reserve the right to modify these terms at any time.\\n\\nWe will notify you of any changes by posting the new terms on this page.',
    'terms.contact.title': 'Contact Information',
    'terms.contact.content': 'If you have any questions about these terms, please contact us at legal@founderis.com.',
    'terms.questions.title': 'Questions about our terms?',
    'terms.questions.description': 'If you have any questions about our terms of service, please contact our legal team.',
    'terms.questions.button': 'Contact Legal Team'
  },
  es: {
    // Navigation
    'nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',

    // Hero Section
    'hero.badge': 'Inteligencia Startup Potenciada por IA',
    'hero.title.part1': 'Founder',
    'hero.title.part2': 'Is',
    'hero.words.innovate': 'Innova',
    'hero.words.create': 'Crea',
    'hero.words.validate': 'Valida',
    'hero.words.launch': 'Lanza',
    'hero.words.scale': 'Escala',
    'hero.description': 'Tu compañero inteligente potenciado por IA que te guía desde',
    'hero.description.highlight': ' la chispa inicial hasta el éxito del mercado',
    'hero.description.end': ' — ofreciendo insights estratégicos, marcos de validación y apoyo emocional en cada paso del camino.',
    'hero.button.start': 'Comienza gratis',
    'hero.stats.features': 'Funciones IA',
    'hero.stats.success': 'Tasa de Éxito',
    'hero.stats.support': 'Soporte Estratégico',

    // Benefits Section
    'benefits.badge': 'Por qué elegir FounderIs',
    'benefits.title': 'Tu ecosistema completo de',
    'benefits.title.highlight': 'soporte para startups',
    'benefits.description': 'Desde lluvia de ideas inicial hasta validación de mercado, planificación estratégica hasta resistencia emocional — FounderIs proporciona la guía integral que los fundadores solitarios necesitan para tener éxito.',
    'benefits.vision.title': 'Socio de Visión',
    'benefits.vision.description': 'Sesiones interactivas de lluvia de ideas que ayudan a refinar tus ideas, explorar oportunidades inexploradas y cristalizar tu propuesta de valor central.',
    'benefits.market.title': 'Brújula de Mercado',
    'benefits.market.description': 'Marcos de validación guiada y pruebas de hipótesis para asegurar el ajuste producto-mercado antes de invertir tiempo y recursos.',
    'benefits.strategic.title': 'Planificador Estratégico',
    'benefits.strategic.description': 'Planificación empresarial estructurada, proyecciones financieras y hojas de ruta accionables que te mantienen enfocado en lo que más importa.',
    'benefits.decision.title': 'Laboratorio de Decisiones',
    'benefits.decision.description': 'Simulaciones de escenarios y análisis pre-mortem que te ayudan a anticipar desafíos y tomar decisiones estratégicas informadas.',
    'benefits.execution.title': 'Optimizador de Ejecución',
    'benefits.execution.description': 'Asistencia en comunicación, insights de productividad e identificación de cuellos de botella para maximizar tu eficiencia e impacto.',
    'benefits.emotional.title': 'Ancla Emocional',
    'benefits.emotional.description': 'Espacio de apoyo confidencial 24/7 que ofrece motivación, manejo del estrés y construcción de resistencia para el viaje del fundador.',
    'benefits.button': 'Experimenta el Poder',

    // How It Works Section
    'howworks.badge': 'Cómo Funciona',
    'howworks.title': 'Tu viaje desde',
    'howworks.title.highlight': 'chispa hasta éxito',
    'howworks.description': 'Tres pilares fundamentales de apoyo que proporcionan guía integral, insights de validación y resistencia emocional para fundadores solitarios.',
    'howworks.step1.title': 'Sociedad de Pensamiento',
    'howworks.step1.description': 'Participa en sesiones interactivas de lluvia de ideas para aclarar tu visión, refinar tu propuesta de valor y desarrollar planes estratégicos.',
    'howworks.step1.detail1': 'Refinamiento interactivo de ideas',
    'howworks.step1.detail2': 'Desarrollo de propuesta de valor',
    'howworks.step1.detail3': 'Asistencia en planificación estratégica',
    'howworks.step1.detail4': 'Soporte de comunicación y pitch',
    'howworks.step2.title': 'Marco de Validación',
    'howworks.step2.description': 'Diseña y ejecuta experimentos de validación de mercado con investigación guiada por IA para probar el ajuste producto-mercado.',
    'howworks.step2.detail1': 'Diseño de pruebas de hipótesis',
    'howworks.step2.detail2': 'Guía de investigación de mercado',
    'howworks.step2.detail3': 'Análisis de feedback de clientes',
    'howworks.step2.detail4': 'Herramientas de evaluación de demanda',
    'howworks.step3.title': 'Apoyo Continuo',
    'howworks.step3.description': 'Accede a apoyo emocional continuo, optimización de productividad y guía estratégica durante todo tu viaje como fundador.',
    'howworks.step3.detail1': 'Apoyo emocional confidencial',
    'howworks.step3.detail2': 'Coaching de productividad y enfoque',
    'howworks.step3.detail3': 'Técnicas de manejo del estrés',
    'howworks.step3.detail4': 'Refuerzo motivacional',
    'howworks.button': 'Comienza tu Viaje',
    'howworks.subtitle': 'Únete a fundadores solitarios que ya no viajan solos',

    // Footer Section
    'footer.badge': '¿Listo para Transformar?',
    'footer.title': '¿Listo para transformar tu',
    'footer.title.highlight': 'viaje como fundador?',
    'footer.description': 'Únete a fundadores solitarios que ya no navegan la incertidumbre solos. Obtén el socio de pensamiento estratégico, marco de validación y apoyo emocional que necesitas para tener éxito.',
    'footer.button.start': 'Comienza a Construir Hoy',
    'footer.brand.description': 'Tu socio de pensamiento potenciado por IA proporcionando guía estratégica, marcos de validación y apoyo emocional para fundadores solitarios.',
    'footer.platform': 'Plataforma',
    'footer.company': 'Empresa',
    'footer.copyright': '© 2024 FounderIs. Todos los derechos reservados.',
    'footer.features': 'Características',
    'footer.pricing': 'Precios',
    'footer.stories': 'Historias de Éxito',
    'footer.documentation': 'Documentación',
    'footer.about': 'Acerca de',
    'footer.careers': 'Carreras',
    'footer.contact': 'Contacto',
    'footer.privacy': 'Privacidad',
    
    // Import all Spanish translations from separate file
    ...require('./SpanishTranslations').spanishTranslations
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}